### ISSUE TITLE
readme 파일 내용 조금 더 추가하세요.

### ISSUE THREAD

**Issue by mocona** [ProjectInTheClass/MatZyp#24]
제목 그대로, readme 파일 내용 조금 더 추가하세요.

한줄정도, 어떤 앱인지 소개하는 내용 넣어주세요.

이름만 봐서는 뭔지 바로 안떠오른답니다.

**Comment by dlwogns0128** [comment]
e5bb3cec5b7b5fd9b34fb2cc73dfea9285e740aa
완료하였습니다
